Repository UniqueNetwork/unique-marketplace-api, pull requests merged in 2022-06, with the labels that each got.

#182 Changed user authorization structure
  package-lock.json
  package.json
  src/admin/admin.controller.ts
  src/admin/admin.service.ts
  src/admin/guards/login.guard.ts
  src/main.ts
Labels: enhancement

#184 feat: Added MarketType into the settings field
  docs/market-type.md
  package.json
  src/app.module.ts
  src/entity/settings.ts
  src/migrations/MarketTypeSettings_20220608000000.ts
  src/settings/dto/settings.dto.ts
  src/settings/interfaces/market.interface.ts
  src/settings/market.service.ts
  src/settings/settings.controller.ts
  src/settings/settings.service.ts
Labels: enhancement

#169 Fix import web3 lib and refactoring
  .eslintrc.js
  package-lock.json
  package.json
  src/admin/servises/web3.service.ts
  src/escrow/kusama.ts
  src/escrow/service.ts
  src/settings/settings.service.ts
  src/utils/blockchain/index.ts
  src/utils/blockchain/kusama.ts
  src/utils/blockchain/polka.ts
  src/utils/blockchain/signTransaction.ts
  src/utils/blockchain/unique.ts
  src/utils/blockchain/util.ts
  src/utils/blockchain/web3.ts
  src/utils/playground/deploy_contract.ts
  tests/auction/auction-canceling.test.ts
  tests/auction/auction-closing.test.ts
  tests/auction/auction-validation.test.ts
  tests/auction/auction.test.ts
  tests/auction/base.ts
  tests/data/base.ts
  tests/escrow.unique.test.ts
  tests/offer.handler.test.ts
  tests/trades.handler.test.ts
  tsconfig.json
Labels: enhancement

#193 Show version on start
  package.json
  src/main.ts
Labels: enhancement

#213 Feature/add trades info to auctions
  package.json
  src/auction/services/auction-creation.service.ts
  src/auction/services/closing/auction-closing.service.ts
  src/entity/market-trade.ts
  src/escrow/service.ts
  src/escrow/unique.ts
  src/migrations/AddMarketTradeInfoInAuctions_20220622000000.ts
Labels: enhancement

#214 feat: mass cancel endpoint for secondary market
  docs/mass_cancel.md
  package.json
  src/admin/admin.controller.ts
  src/admin/dto/index.ts
  src/admin/dto/mass-cancel.dto.ts
  src/admin/servises/index.ts
  src/admin/servises/mass-canceling.service.ts
  src/admin/servises/mass-sale.service.ts
  src/app.module.ts
  src/escrow/constants.ts
Labels: enhancement

#212 Feature/modulation
  package-lock.json
  package.json
  src/admin/admin.controller.ts
  src/admin/admin.health.ts
  src/admin/admin.module.ts
  src/admin/services/admin.service.ts
  src/admin/services/collections.service.ts
  src/admin/services/index.ts
  src/admin/services/mass-canceling.service.ts
  src/admin/services/mass-sale.service.ts
  src/admin/services/tokens.service.ts
  src/app.module.ts
  src/auction/auction.controller.ts
  src/auction/auction.module.ts
  src/auction/providers/auction-credentials.provider.ts
  src/auction/providers/index.ts
  src/auction/services/auction-canceling.service.ts
  src/auction/services/auction-creation.service.ts
  src/auction/services/bid-placing.service.ts
  src/auction/services/bid-withdraw.service.ts
  src/auction/services/closing/auction-closing.service.ts
  src/auction/services/helpers/tx-decoder.ts
  src/auction/services/search-index.service.ts
  src/blockchain/blockchain.injectors.ts
  src/blockchain/blockchain.module.ts
  src/blockchain/constants.ts
  src/blockchain/index.ts
  src/offers/dto/index.ts
  src/offers/interfaces/index.ts
  src/offers/offers.controller.ts
  src/offers/offers.module.ts
  src/offers/offers.service.ts
  src/offers/pipes/index.ts
  src/settings/dto/index.ts
  src/settings/index.ts
  src/settings/settings.controller.ts
  src/settings/settings.module.ts
  src/settings/settings.service.ts
  src/trades/dto/index.ts
  src/trades/interfaces/index.ts
  src/trades/pipes/index.ts
  src/trades/trades.controller.ts
  src/trades/trades.module.ts
  src/trades/trades.service.ts
  src/utils/health/health.service.ts
  tests/escrow.unique.test.ts
Labels: enhancement

#204 feat: nonce for auction transactions
  docs/mass_fixprice_sale.md
  package-lock.json
  package.json
  src/admin/dto/collections.dto.ts
  src/auction/services/auction-canceling.service.ts
  src/auction/services/auction-creation.service.ts
  src/auction/services/bid-withdraw.service.ts
  src/auction/services/closing/auction-closing.service.ts
Labels: bug

#215 Fix/escrow test ends and run all tests
  jest.config.ts
  package.json
  tests/escrow.unique.test.ts
  tests/jest.config.json
  tests/resolver.js
  tsconfig.json
Labels: bug

#217 Refactored environment structure, data moved to env file
  .env-local
  docker-compose.example.yml
  docker-compose.hub.yml
  package-lock.json
  package.json
  tests/offer.handler.test.ts
Labels: enhancement, env

#220 Fixed run tests
  package.json
  tests/jest.config.ts
  tsconfig.json
Labels: bug

#219 Feature/MAR-636,619,618,568
  docs/admin_tokens_allowed.md
  docs/calculation.md
  package.json
  src/admin/admin.module.ts
  src/admin/services/index.ts
  src/admin/services/market.service.ts
  src/admin/services/mass-canceling.service.ts
  src/admin/services/mass-sale.service.ts
  src/admin/services/tokens.service.ts
  src/auction/requests/calculate.ts
  src/auction/responses/bids.ts
  src/config/market-config.ts
  src/offers/dto/offer-dto.ts
  src/utils/blockchain/util.ts
Labels: bug, enhancement

#227 Feature/commands
  .prettierrc
  package-lock.json
  package.json
  src/admin/services/mass-sale.service.ts
  src/admin/services/tokens.service.ts
  src/auction/auction.controller.ts
  src/cli.module.ts
  src/commands/cli.command.ts
  src/commands/interfaces/collection.interface.ts
  src/commands/services/check-config.service.ts
  src/commands/services/collection.service.ts
  src/commands/services/deploy-contract.service.ts
  src/utils/blockchain/util.ts
Labels: enhancement

#232 Fix/auction transfer to winner
  package.json
  src/auction/services/closing/auction-closing.service.ts
Labels: bug

#237 hotfix/v1.5.6_MAR-655
  package.json
  src/auction/services/bid-placing.service.ts
Labels: bug
